export const APP_ID = '129401a1';
export const API_KEY='0e32cfd7e1f81e84eab471ae5deb3237';

const GET_RECIPES_START = 'GET_RECIPES_START'
const GET_RECIPES_SUCCESS = 'GET_RECIPES_SUCCESS'
const GET_RECIPES = 'GET_RECIPES';
const CHANGE_TYPE = 'CHANGE_TYPE';

export {GET_RECIPES_SUCCESS, GET_RECIPES_START, GET_RECIPES, CHANGE_TYPE}
